apiVersion: apps/v1
kind: Deployment
metadata:
  name: dotnet-app
  namespace: dotnet
spec:
  replicas: 3
  selector:
    matchLabels:
      app: dotnet-app
  template:
    metadata:
      labels:
        app: dotnet-app
    spec:
      containers:
      - name: dotnet-app
        image: kunalbarot3188/dotnet-image:v1
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: dotnet-service
  namespace: dotnet
spec:
  selector:
    app: dotnet-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30003  # Unique nodePort for .NET Core application
  type: NodePort
